name: book_borrowing_app
description: A Flutter app for book borrowing management
version: 1.0.0
publish_to: 'none' # Remove this line if you want to publish your package

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0  # Pastikan versinya sesuai
  sqflite_common_ffi: ^2.0.0
  sqflite: ^2.2.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add any assets or images you need in your project
  assets:
    - assets/images/

# Optional: Add fonts if required
# fonts:
#   - family: Roboto
#     fonts:
#       - asset: fonts/Roboto-Regular.ttf
#       - asset: fonts/Roboto-Italic.ttf
#         weight: 400
#         style: italic
